### ISSUE TITLE
Accordion Lag, Ripple effect on button bad animation

### ISSUE THREAD

**Issue by nacasha** [nyancodeid/nyancss#2]
Both multiple and single accordion is very lag, sometimes when i click the accordion, it won't open
And ripple effect on button just looping rather than creating a new ripple if i click it quickly, it looks bad

My Browser : Chrome Version 57.0.2987.98 (64-bit)

**Comment by hibuno** [comment]
Hello nacasha,

can you explain what version of nyan you use?

**Comment by nacasha** [comment]
I test it through the demo,
if i use it on my local development, will it fix the lag?

https://nyancodeid.github.io/nyancss/demo/index.html#accordion

**Comment by nyancodeid** [comment]
Hai Nacasha, thanks for created issue. Just wait for moment until next update. Your issue under review. Ok.
Thanks for usung NyanCSS 
nyan ~
